// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhhgmXP_tClWVQ63Tnkyj8FHInm7xPBOE',
    appId: '1:56797707286:web:e01759037fd78194bc0937',
    messagingSenderId: '56797707286',
    projectId: 'chat-app-198e2',
    authDomain: 'chat-app-198e2.firebaseapp.com',
    storageBucket: 'chat-app-198e2.firebasestorage.app',
    measurementId: 'G-P56K5BJ3Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZtscpAVRmLvZg1wIMi2RJ8QRIJTYR19E',
    appId: '1:56797707286:android:da276bfa7e83e5f1bc0937',
    messagingSenderId: '56797707286',
    projectId: 'chat-app-198e2',
    storageBucket: 'chat-app-198e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxTicBzADlHG79fNc-5c2uK3GYynWUW54',
    appId: '1:56797707286:ios:1f222febe3def035bc0937',
    messagingSenderId: '56797707286',
    projectId: 'chat-app-198e2',
    storageBucket: 'chat-app-198e2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxTicBzADlHG79fNc-5c2uK3GYynWUW54',
    appId: '1:56797707286:ios:1f222febe3def035bc0937',
    messagingSenderId: '56797707286',
    projectId: 'chat-app-198e2',
    storageBucket: 'chat-app-198e2.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhhgmXP_tClWVQ63Tnkyj8FHInm7xPBOE',
    appId: '1:56797707286:web:2ae7d972eede1c13bc0937',
    messagingSenderId: '56797707286',
    projectId: 'chat-app-198e2',
    authDomain: 'chat-app-198e2.firebaseapp.com',
    storageBucket: 'chat-app-198e2.firebasestorage.app',
    measurementId: 'G-LC51PJDK6G',
  );
}
